namespace BeepPayment.ConsumeAPI.Models.Dto;

public class PostPaymentPacketDto //: CredentialDto
{
    
    //This is the product code used in identifying the service the customer is consuming e.g. TIGOAIRTIME
    public string ServiceCode { get; set; }

    //The mobile number of the customer performing the payment. The MSISDN should begin with a country code e.g. 254xxxxxxxxx
    public string MSISDN { get; set; }

    //The reference ID generated by the receiver (merchant) client system for the transaction.
    public string? InvoiceNumber { get; set; }

    //Account number is the recipient of payment . If it’s a mobile number it should begin with a country code e.g. 254xxxxxxxxx
    public string AccountNumber { get; set; }

    //The unique transactionID generated by the bank for this transaction.
    public string PayerTransactionID { get; set; }

    //The amount paid by the customer.
    public double Amount { get; set; }

    //A narration of the payment being made.
    public string? Narration { get; set; }

    //The date the payer received payment. yyyy-mm-dd hh:mm:ss.
    public string DatePaymentReceived { get; set; }

    //The ISO code for the transaction currency.
    public string CurrencyCode { get; set; }

    //Unique hub transaction ID
    public string? HubID { get; set; }

    //The payment mode used for example ATM, Mobile, etc
    public string? PaymentMode { get; set; }

    //The name of the customer as given on the payer’s end
    public string? CustomerNames { get; set; }

    //Any extra parameter or information you need to pass in a key-value JSON format i.e. callBackUrl
    public string? ExtraData { get; set; }
}