namespace BeepPayment.ConsumeAPI.Models;

public class TransactionStatus
{

    public int Id { get; set; }
    
    //The status of this transaction within the Beep system.
    public int StatusCode { get; set; }
    //A narration / description for the status code above.
    public string StatusDescription { get; set; }
    //The unique ID / reference generated by bank for this transaction.
    public string PayerTransactionID { get; set; }
    //The unique reference ID generated by the Beep Server for this transaction.
    public int BeepTransactionID { get; set; }
    //The reference ID generated for this transaction by the merchant system.
    public string InvoiceNumber { get; set; }
}